from .delete_zam_mz        import delete_zam_mz
from .no_snils             import no_snils
from .bez_izhoda           import bez_izhoda 
from .bez_ambulat_level    import bez_ambulat_level
from .no_OMS               import no_OMS
from .neveren_vid_lechenia import neveren_vid_lechenia
from .no_lab               import no_lab
from .net_diagnoz_covid    import net_diagnoz_covid
from .no_pad               import no_pad
from .net_dnevnik          import net_dnevnik
from .zavishie_statusy     import zavishie_statusy
from .load_snils_comment   import load_snils_comment
from .ivl                  import IVL
from .zamechania           import zamechania
from .zamechania_file      import zamechania_file
from .zam_status           import zamechania_stat
from .sverka_fr_otcheta    import sverka_fr_otcheta
