SELECT
	r.BDATE day,
	a.AGNNAME organization,
	i.CODE pokazatel,
	CASE WHEN STRVAL  IS NOT NULL THEN STRVAL
		WHEN NUMVAL  IS NOT NULL THEN CAST(NUMVAL  AS varchar(30))
		WHEN DATEVAL IS NOT NULL THEN CAST(DATEVAL AS varchar(30))
		ELSE NULL END value
		
	FROM PARUS.BLTBLVALUES v
		INNER JOIN PARUS.BLTABLESIND si
		on(v.BLTABLESIND = si.RN)
		INNER JOIN (SELECT * FROM PARUS.BALANCEINDEXES
						WHERE CODE LIKE 'exp_test_%' ) i
		on(si.BALANCEINDEXES = i.RN)
		INNER JOIN (SELECT PRN, RN, NUMB  FROM  PARUS.BLTBLROWS  ) ro
		on(v.PRN = ro.RN)
		INNER JOIN PARUS.BLSUBREPORTS s
		on(ro.PRN = s.RN)
		INNER JOIN (SELECT * FROM PARUS.BLREPORTS 
						WHERE BDATE =  trunc(SYSDATE))  r
		on(s.PRN = r.RN)
		INNER JOIN PARUS.AGNLIST a
		on(r.AGENT = a.RN)
		INNER JOIN PARUS.BLREPFORMED rd
		on(r.BLREPFORMED = rd.RN)
		INNER JOIN (SELECT * FROM PARUS.BLREPFORM
						WHERE CODE = '54 COVID 19 NEW' ) rf
		on(rd.PRN = rf.RN)
